apiVersion: v1
kind: Service
metadata:
  name: mlbrFtPrnts
  labels:
    app: mlbrFtPrnts
spec:
  ports:
    - port: 80
  selector:
    app: mlbrFtPrnts
    tier: frontend
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: mlbrFtPrnts
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mlbrFtPrnts
  labels:
    app: mlbrFtPrnts
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mlbrFtPrnts
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.9.7-apache
        name: mlbrFtPrnts
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password.txt
        ports:
        - containerPort: 80
          name: mlbrFtPrnts
        volumeMounts:
        - name: mlbrFtPrnts-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: mlbrFtPrnts-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim